name: Publish blog
on:
  push:
    branches:    
      - main
jobs:
  Build-Blog-Pages:
    name: build pages
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install and Build
        run: |
          git submodule init
          git submodule update
          npm install
          npm run build
      - name: Publish
        run: cp -rf ./public /home/ubuntu/website/iknil.dev/html/